### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Charlie-robin** [CarapaceonBear/calculator_web_app#5]
# Feedback

Hey Charlie here, feel free to message me on Slack if you want any clarification on the points below. I will give you both positive and constructive feedback on your project.

---

## Lets Build

- A working Calculator - 110% DONE
- Practice using Git and GitHub flow - 110% DONE
  - Having a branching strategy is great, keep this up :)
- Apply what you are learning?
  - SCSS - DONE
  - BEM - DONE

## Requirements

- PSEUDOCODE - DONE
- Github Repo:
  - README.md - DONE
  - 15 commits - DONE
- Accept a minimum of 2 inputs, perform an operation and return the output. - DONE
- DO NOT USE `eval()` - DONE
- Mobile-first - DONE
- No copying code / using a tutorial as your own work - DONE

---

### Positive

- Soooo many nice features!
- Your readme is brilliant
- Looks nice, great use of colors for both the dark and light modes.
  - Using shade to distinguish numbers from operators, works very well.
- Adding a link to the Github repo is a very nice touch.
  - Could you also add a link to your portfolio?
  - It's great to see you understand how to use a CDN like font-awesome.
- BEM!!! Great you are correctly using blocks, elements, and modifiers. Keep it up!
- SCSS is on point, it is very modular and you are using all the benefits it gives you, nesting, & selector, and variables. Keep this up!
  - Great use of mixins as utility classes
  - This is a stretch goal but if you have time have a look at this article [Mixin Media queries](https://davidwalsh.name/write-media-queries-sass) Mixin media queries :).

### Constructive

- Have a look at [CSS Transitions](https://www.w3schools.com/css/css3_transitions.asp), it would be great to have a gentler transition from light to dark mode.
- Add a link to the hosted site on your readme.
- Remove any unused media queries from your code.

- You shouldn't need to wrap every single individual HTML element with a `<div/>`. So with your buttons, it doesn't look like you are styling the `<div/>`'s with anything that you couldn't just add to the button.

  - `<div/>`'s are for grouping / dividing your HTML elements to add styles. [w3](https://www.w3schools.com/tags/tag_div.asp)
  - `<div/>`'s are great but you don't always need them.

---

### Positive

- You have grouped and labeled your code so it is easy to navigate.
- All of your functions have descriptive names which make them easier to understand as I read through the code.
- I feel confident with your understanding of variables, arrays, loops, and objects.
- I am confident in your understanding of the DOM, you are able to get, interact and set up events on your HTML elements.
- You have managed to get **a lot** of functionality into this project, and I can see you are eager to add more. Keep this up and come back and add to it as you go through the course!

### Constructive

- You love a `for` loop. There is nothing wrong with that. You do have access to iterators that will make your code more Declarative, rather than Imperative. With Declarative, your code is more focused on the 'what' rather than the 'how' it is doing it. It is only an opinion though so it is your choice.

  ```js
  // app.js
  // CAN YOU WRITE THIS WITH REDUCE?
  const countSymbols = (section, symbol) => {
    let count = 0;
    for (let i = 0; i < section.length; i++) {
      if (section[i] == symbol) {
        count++;
      }
    }
    return count;
  };

  // CAN YOU WRITE THIS WITH MAP?
  // .map((item, index) => {})
  const replaceNegativeNumbers = segment => {
    let number = segment;
    for (let i = 0; i < number.length; i++) {
      if (number[i] == "n") {
        if (i == 0) {
          number = `-${number.slice(1, number.length)}`;
        } else {
          number = `${number.slice(0, i)}-${number.slice(i + 1, number.length)}`;
        }
      }
    }
    return number;
  };
  ```

- Don't get me wrong the dark-mode and light-mode toggles are great! It is good you have got it working but you can refactor it as it is a brute force implementation.
  - You do not need to get each element and replace its class, you have different options that are easier to implement.
  - You can use [CSS Variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties)
  - It will mean you have to tweak how you have been styling your items.

```scss
// variables.scss

// CSS VARIABLES IN EACH CLASS
// --VARIABLE-NAME IS LIKE CREATING A CUSTOM PROPERTY AND VALUE
.dark-mode {
  --background-color: #130512;
  --display-color: #583a56;
  --button-color-1: #431c3d;
  --button-color-2: #60335d;
  --button-color-3: #7f4e7b;
  --button-hover: #98158d;
  --text-color: #ffdcf3;
}

// YOU WANT THE VARIABLES TO BE LABELLED THE SAME IN EACH CLASS
// - WHEN THE CLASS IS USED ONLY THE VALUE CHANGES

.light-mode {
  --background-color: #ffdcf3;
  --display-color: #eda8c6;
  --button-color-1: #dd658b;
  --button-color-2: #e89bb1;
  --button-color-3: #f6bcd0;
  --button-hover: #f13570;
  --text-color: #1f081d;
}
```

- You set up the CSS variables ^^, then use them in your styles using a CSS function that gets you the value of the variable -> `var(--VARIABLE-NAME)`.

```scss
// _components.scss
.main {
  &__button {
    // THIS IS HOW YOU USE A CSS VARIABLE
    // - PASS IN THE VARIABLE YOU WANT IT WILL GIVE YOU THE VALUE
    color: var(--text-color);

    &:hover {
      // ANOTHER EXAMPLE
      background-color: var(--button-hover);
    }
  }
}
```

- So based on whatever class is being used it will pick that variable and its value.
- `--text-color` will be either:

  - `.light-mode` -> this value `#1f081d`.
  - `.dark-mode` -> this value `#ffdcf3`.

- This means with your JS handle functions you only need to add the correct class to the body. You will also have to show and hide your buttons.

```js
// app.js

const onLightModeClicked = () => {
  darkModeButton.classList.toggle("hide-button");
  lightModeButton.classList.toggle("hide-button");
  body.classList.replace("dark-mode", "light-mode");
};

const onDarkModeClicked = () => {
  darkModeButton.classList.toggle("hide-button");
  lightModeButton.classList.toggle("hide-button");
  body.classList.replace("light-mode", "dark-mode");
};
```

- This is pretty hard to explain without a working example have a look at my [code pen](https://codepen.io/charlie-robin/pen/jOrBdLY) Feel free to ask any questions :).

---
